"""Add phone_number to ConversationState

Revision ID: 2022a6eb3a26
Revises: 39127c680eda
Create Date: 2026-07-16 17:16:24.016441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2022a6eb3a26'
down_revision: Union[str, Sequence[str], None] = '39127c680eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE conversation_state CASCADE')
    op.add_column('conversation_state', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.alter_column('conversation_state', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversation_state', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_conversation_state_phone_number'), 'conversation_state', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_state_phone_number'), table_name='conversation_state')
    op.alter_column('conversation_state', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_state', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('conversation_state', 'phone_number')
    # ### end Alembic commands ###
