"""add_recommendation_expiry_impact

Revision ID: 270f8d0f0940
Revises: 28600394a7ca
Create Date: 2026-07-18 10:45:46.977008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270f8d0f0940'
down_revision: Union[str, Sequence[str], None] = '28600394a7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_price_recommendations', sa.Column('impact', sa.JSON(), nullable=True))
    op.add_column('market_price_recommendations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_price_recommendations', 'expires_at')
    op.drop_column('market_price_recommendations', 'impact')
    # ### end Alembic commands ###
