"""add_market_intelligence_engine

Revision ID: 28600394a7ca
Revises: 2b29aea62b04
Create Date: 2026-07-18 10:12:30.886140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28600394a7ca'
down_revision: Union[str, Sequence[str], None] = '2b29aea62b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('analysis_status', sa.String(length=32), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('summary', sa.String(length=1024), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_snapshots_tenant_captured', 'market_snapshots', ['tenant_id', 'captured_at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_tenant_id'), 'market_snapshots', ['tenant_id'], unique=False)
    op.create_table('market_price_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recommended_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['market_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_recommendations_snapshot_id'), 'market_price_recommendations', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_market_price_recommendations_tenant_id'), 'market_price_recommendations', ['tenant_id'], unique=False)
    op.create_index('ix_market_recommendations_tenant_status', 'market_price_recommendations', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_recommendations_tenant_status', table_name='market_price_recommendations')
    op.drop_index(op.f('ix_market_price_recommendations_tenant_id'), table_name='market_price_recommendations')
    op.drop_index(op.f('ix_market_price_recommendations_snapshot_id'), table_name='market_price_recommendations')
    op.drop_table('market_price_recommendations')
    op.drop_index(op.f('ix_market_snapshots_tenant_id'), table_name='market_snapshots')
    op.drop_index('ix_market_snapshots_tenant_captured', table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
