"""Add onboarding_completed to BusinessProfile

Revision ID: 2b29aea62b04
Revises: 8352754ff38f
Create Date: 2026-07-18 09:46:09.418011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b29aea62b04'
down_revision: Union[str, Sequence[str], None] = '8352754ff38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('onboarding_completed', sa.Boolean(), server_default='true', nullable=False))
    op.create_foreign_key(None, 'pricing_quote_items', 'pricing_quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pricing_quote_items', type_='foreignkey')
    op.drop_column('business_profiles', 'onboarding_completed')
    # ### end Alembic commands ###
