"""add_onboarding_events_and_seq

Revision ID: 39127c680eda
Revises: ca06de83189a
Create Date: 2026-07-16 14:24:24.050972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39127c680eda'
down_revision: Union[str, Sequence[str], None] = 'ca06de83189a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_onboarding_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['retailer_onboarding_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE SEQUENCE IF NOT EXISTS retailer_id_seq START WITH 241")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retailer_onboarding_events')
    op.execute("DROP SEQUENCE IF NOT EXISTS retailer_id_seq")
    # ### end Alembic commands ###
