"""init

Revision ID: 73d08f9fe377
Revises: 
Create Date: 2026-07-05 20:19:32.567527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73d08f9fe377'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_snippet', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('order_source', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_prices',
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('item_type')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_forecasts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('predicted_demand_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_demand_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('historical_context', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('hub_location', sa.String(length=255), nullable=True),
    sa.Column('base_price_today', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('default_credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('iot_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('financial_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('app_language', sa.String(length=50), nullable=False),
    sa.Column('profile_pic_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_tenant_id'), 'business_profiles', ['tenant_id'], unique=True)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('bird_type', sa.String(length=100), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mortality_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'driver', 'retailer', name='user_role', create_constraint=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('shop_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('whatsapp_id')
    )
    op.create_table('trucks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=True),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('iot_device_id', sa.String(length=100), nullable=True),
    sa.Column('max_capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iot_device_id')
    )
    op.create_table('iot_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('truck_id', sa.Uuid(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('retailer_id', sa.UUID(), nullable=True),
    sa.Column('truck_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('order_source', sa.String(length=20), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['truck_id'], ['trucks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('khata_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('charge', 'payment', 'adjustment', name='transaction_type', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('khata_transactions')
    op.drop_table('orders')
    op.drop_table('iot_readings')
    op.drop_table('trucks')
    op.drop_table('users')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_business_profiles_tenant_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_table('ai_forecasts')
    op.drop_table('tenants')
    op.drop_table('product_prices')
    op.drop_table('error_logs')
    op.drop_table('classification_logs')
    # ### end Alembic commands ###
