"""remove pending price and total from conversation state

Revision ID: 8352754ff38f
Revises: 2022a6eb3a26
Create Date: 2026-07-16 17:34:03.421968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8352754ff38f'
down_revision: Union[str, Sequence[str], None] = '2022a6eb3a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_state', 'pending_price_per_kg')
    op.drop_column('conversation_state', 'pending_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_state', sa.Column('pending_total', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('conversation_state', sa.Column('pending_price_per_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
