"""Add retailer onboarding pipeline

Revision ID: ca06de83189a
Revises: 3fa79271cad2
Create Date: 2026-07-16 13:32:07.510469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca06de83189a'
down_revision: Union[str, Sequence[str], None] = '3fa79271cad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retailer_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('invite_code', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('QR_DASHBOARD', 'QR_DRIVER', name='invite_source', create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'OPENED', 'ONBOARDING', 'USED', 'EXPIRED', 'CANCELLED', name='invite_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retailer_invitations_invite_code'), 'retailer_invitations', ['invite_code'], unique=True)
    op.create_table('retailer_onboarding_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('invite_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('shop_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='draft_status', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['retailer_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inventory')
    op.create_index('ix_comm_kpi_tenant_date', 'analytics_communication_daily_kpi', ['tenant_id', 'metric_date'], unique=False)
    op.drop_constraint(op.f('uq_analytics_event_processed_tenant_event'), 'analytics_events_processed', type_='unique')
    op.create_unique_constraint('uq_analytics_event_processed', 'analytics_events_processed', ['tenant_id', 'event_id'])
    op.create_index('ix_fin_kpi_tenant_date', 'analytics_financial_daily_kpi', ['tenant_id', 'metric_date'], unique=False)
    op.create_index('ix_oper_kpi_tenant_date', 'analytics_operational_daily_kpi', ['tenant_id', 'metric_date'], unique=False)
    op.create_index('ix_comm_log_tenant_status', 'communication_logs', ['tenant_id', 'status'], unique=False)
    op.alter_column('integration_outbox', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('integration_outbox_event_id_key'), 'integration_outbox', type_='unique')
    op.drop_index(op.f('ix_outbox_tenant_status_retry'), table_name='integration_outbox')
    op.drop_index(op.f('ix_integration_outbox_event_id'), table_name='integration_outbox')
    op.create_index(op.f('ix_integration_outbox_event_id'), 'integration_outbox', ['event_id'], unique=True)
    op.create_foreign_key(None, 'integration_outbox', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_inventory_transactions_created_at'), 'inventory_transactions', ['created_at'], unique=False)
    op.add_column('khata_customer_balances', sa.Column('last_entry_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('uq_khata_balance_tenant_customer'), 'khata_customer_balances', type_='unique')
    op.create_unique_constraint('uq_customer_balance_projection', 'khata_customer_balances', ['tenant_id', 'customer_id'])
    op.drop_column('khata_customer_balances', 'last_ledger_entry_id')
    op.drop_column('khata_customer_balances', 'last_rebuilt_at')
    op.add_column('khata_ledgers', sa.Column('id', sa.Uuid(), nullable=False))
    op.add_column('khata_ledgers', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('khata_ledgers', 'reference_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('khata_ledgers', 'reference_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index('ix_khata_ledger_tenant_customer', 'khata_ledgers', ['tenant_id', 'customer_id'], unique=False)
    op.drop_column('khata_ledgers', 'occurred_at')
    op.drop_column('khata_ledgers', 'entry_id')
    op.alter_column('orders', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'retailer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'dispatch_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_customer_price_override_tenant_cust_sku'), 'pricing_customer_overrides', type_='unique')
    op.drop_column('pricing_customer_overrides', 'updated_at')
    op.drop_column('pricing_customer_overrides', 'valid_from')
    op.drop_column('pricing_customer_overrides', 'created_at')
    op.drop_index(op.f('ix_pricing_price_book_entries_sku'), table_name='pricing_price_book_entries')
    op.drop_constraint(op.f('uq_price_book_entry_sku_qty'), 'pricing_price_book_entries', type_='unique')
    op.drop_constraint(op.f('pricing_price_book_entries_price_book_id_fkey'), 'pricing_price_book_entries', type_='foreignkey')
    op.alter_column('pricing_price_books', 'effective_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               nullable=False)
    op.drop_constraint(op.f('uq_pricing_price_book_tenant_name'), 'pricing_price_books', type_='unique')
    op.create_unique_constraint('uq_price_book_tenant_name', 'pricing_price_books', ['tenant_id', 'name'])
    op.drop_column('pricing_price_books', 'currency')
    op.drop_column('pricing_price_history', 'changed_by')
    op.drop_constraint(op.f('pricing_quote_items_quote_id_fkey'), 'pricing_quote_items', type_='foreignkey')
    op.drop_constraint(op.f('uq_pricing_quote_tenant_num_ver'), 'pricing_quotes', type_='unique')
    op.create_index('ix_quote_tenant_status', 'pricing_quotes', ['tenant_id', 'status'], unique=False)
    op.create_unique_constraint('uq_quote_tenant_number', 'pricing_quotes', ['tenant_id', 'quote_number'])
    op.drop_constraint(op.f('uq_pricing_zone_surcharge_tenant_zone'), 'pricing_zone_surcharges', type_='unique')
    op.drop_column('pricing_zone_surcharges', 'updated_at')
    op.drop_column('pricing_zone_surcharges', 'created_at')
    op.alter_column('product_prices', 'item_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('product_prices', 'price_per_kg',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('product_prices', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tenants', sa.Column('warehouse_latitude', sa.Numeric(precision=10, scale=8), nullable=True))
    op.add_column('tenants', sa.Column('warehouse_longitude', sa.Numeric(precision=11, scale=8), nullable=True))
    op.add_column('users', sa.Column('shop_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('retailer_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('zone', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('onboarding_status', sa.String(length=50), server_default='ACTIVE', nullable=False))
    op.create_unique_constraint(None, 'users', ['retailer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'onboarding_status')
    op.drop_column('users', 'zone')
    op.drop_column('users', 'retailer_id')
    op.drop_column('users', 'shop_name')
    op.drop_column('tenants', 'warehouse_longitude')
    op.drop_column('tenants', 'warehouse_latitude')
    op.alter_column('product_prices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_prices', 'price_per_kg',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('product_prices', 'item_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('pricing_zone_surcharges', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pricing_zone_surcharges', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_pricing_zone_surcharge_tenant_zone'), 'pricing_zone_surcharges', ['tenant_id', 'delivery_zone'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_quote_tenant_number', 'pricing_quotes', type_='unique')
    op.drop_index('ix_quote_tenant_status', table_name='pricing_quotes')
    op.create_unique_constraint(op.f('uq_pricing_quote_tenant_num_ver'), 'pricing_quotes', ['tenant_id', 'quote_number', 'quote_version'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('pricing_quote_items_quote_id_fkey'), 'pricing_quote_items', 'pricing_quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    op.add_column('pricing_price_history', sa.Column('changed_by', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('pricing_price_books', sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_price_book_tenant_name', 'pricing_price_books', type_='unique')
    op.create_unique_constraint(op.f('uq_pricing_price_book_tenant_name'), 'pricing_price_books', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('pricing_price_books', 'effective_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(op.f('pricing_price_book_entries_price_book_id_fkey'), 'pricing_price_book_entries', 'pricing_price_books', ['price_book_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_price_book_entry_sku_qty'), 'pricing_price_book_entries', ['price_book_id', 'sku', 'min_quantity_kg'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pricing_price_book_entries_sku'), 'pricing_price_book_entries', ['sku'], unique=False)
    op.add_column('pricing_customer_overrides', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pricing_customer_overrides', sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pricing_customer_overrides', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_customer_price_override_tenant_cust_sku'), 'pricing_customer_overrides', ['tenant_id', 'customer_id', 'sku'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'dispatch_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'retailer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('khata_ledgers', sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('khata_ledgers', sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index('ix_khata_ledger_tenant_customer', table_name='khata_ledgers')
    op.alter_column('khata_ledgers', 'reference_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('khata_ledgers', 'reference_type',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('khata_ledgers', 'notes')
    op.drop_column('khata_ledgers', 'id')
    op.add_column('khata_customer_balances', sa.Column('last_rebuilt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('khata_customer_balances', sa.Column('last_ledger_entry_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_customer_balance_projection', 'khata_customer_balances', type_='unique')
    op.create_unique_constraint(op.f('uq_khata_balance_tenant_customer'), 'khata_customer_balances', ['tenant_id', 'customer_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('khata_customer_balances', 'last_entry_at')
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.drop_constraint(None, 'integration_outbox', type_='foreignkey')
    op.drop_index(op.f('ix_integration_outbox_event_id'), table_name='integration_outbox')
    op.create_index(op.f('ix_integration_outbox_event_id'), 'integration_outbox', ['event_id'], unique=False)
    op.create_index(op.f('ix_outbox_tenant_status_retry'), 'integration_outbox', ['tenant_id', 'status', 'next_retry_at'], unique=False)
    op.create_unique_constraint(op.f('integration_outbox_event_id_key'), 'integration_outbox', ['event_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('integration_outbox', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_comm_log_tenant_status', table_name='communication_logs')
    op.drop_index('ix_oper_kpi_tenant_date', table_name='analytics_operational_daily_kpi')
    op.drop_index('ix_fin_kpi_tenant_date', table_name='analytics_financial_daily_kpi')
    op.drop_constraint('uq_analytics_event_processed', 'analytics_events_processed', type_='unique')
    op.create_unique_constraint(op.f('uq_analytics_event_processed_tenant_event'), 'analytics_events_processed', ['tenant_id', 'event_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_comm_kpi_tenant_date', table_name='analytics_communication_daily_kpi')
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bird_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quantity_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('mortality_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    op.drop_table('retailer_onboarding_drafts')
    op.drop_index(op.f('ix_retailer_invitations_invite_code'), table_name='retailer_invitations')
    op.drop_table('retailer_invitations')
    # ### end Alembic commands ###
