"""add preferred language

Revision ID: d5b16e54ad00
Revises: c3d4e5f6a7b8
Create Date: 2026-07-16 06:26:01.279023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5b16e54ad00'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    from sqlalchemy import inspect
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    # Safely add preferred_language if it doesn't exist
    if 'users' in tables:
        columns = [c['name'] for c in inspector.get_columns('users')]
        if 'preferred_language' not in columns:
            op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=True))
            
    # We skip all other operations in this migration because production DB is out of sync and already has them.
    
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.alter_column('product_prices', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_prices', 'price_per_kg',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('product_prices', 'item_type',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('pricing_zone_surcharges', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pricing_zone_surcharges', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_pricing_zone_surcharge_tenant_zone'), 'pricing_zone_surcharges', ['tenant_id', 'delivery_zone'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_quote_tenant_number', 'pricing_quotes', type_='unique')
    op.drop_index('ix_quote_tenant_status', table_name='pricing_quotes')
    op.create_unique_constraint(op.f('uq_pricing_quote_tenant_num_ver'), 'pricing_quotes', ['tenant_id', 'quote_number', 'quote_version'], postgresql_nulls_not_distinct=False)
    op.drop_column('pricing_quotes', 'converted_order_id')
    op.create_foreign_key(op.f('pricing_quote_items_quote_id_fkey'), 'pricing_quote_items', 'pricing_quotes', ['quote_id'], ['id'], ondelete='CASCADE')
    op.add_column('pricing_price_books', sa.Column('currency', sa.VARCHAR(length=8), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_price_book_tenant_name', 'pricing_price_books', type_='unique')
    op.create_unique_constraint(op.f('uq_pricing_price_book_tenant_name'), 'pricing_price_books', ['tenant_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('pricing_price_books', 'effective_date')
    op.create_foreign_key(op.f('pricing_price_book_entries_price_book_id_fkey'), 'pricing_price_book_entries', 'pricing_price_books', ['price_book_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_price_book_entry_sku_qty'), 'pricing_price_book_entries', ['price_book_id', 'sku', 'min_quantity_kg'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pricing_price_book_entries_sku'), 'pricing_price_book_entries', ['sku'], unique=False)
    op.add_column('pricing_customer_overrides', sa.Column('valid_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pricing_customer_overrides', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('pricing_customer_overrides', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_customer_price_override_tenant_cust_sku'), 'pricing_customer_overrides', ['tenant_id', 'customer_id', 'sku'], postgresql_nulls_not_distinct=False)
    op.alter_column('orders', 'dispatch_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('orders', 'retailer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_inventory_transactions_created_at'), table_name='inventory_transactions')
    op.add_column('integration_outbox', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('integration_outbox', sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'integration_outbox', type_='foreignkey')
    op.drop_index('ix_outbox_status_created', table_name='integration_outbox')
    op.drop_index(op.f('ix_integration_outbox_status'), table_name='integration_outbox')
    op.drop_index(op.f('ix_integration_outbox_event_type'), table_name='integration_outbox')
    op.drop_index(op.f('ix_integration_outbox_event_id'), table_name='integration_outbox')
    op.drop_index(op.f('ix_integration_outbox_correlation_id'), table_name='integration_outbox')
    op.drop_index(op.f('ix_integration_outbox_aggregate_id'), table_name='integration_outbox')
    op.create_index(op.f('ix_outbox_tenant_status_retry'), 'integration_outbox', ['tenant_id', 'status', 'next_retry_at'], unique=False)
    op.alter_column('integration_outbox', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::character varying"))
    op.alter_column('integration_outbox', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('integration_outbox', 'causation_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('integration_outbox', 'correlation_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('integration_outbox', 'aggregate_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('integration_outbox', 'event_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('integration_outbox', 'created_at')
    op.drop_column('integration_outbox', 'last_error')
    op.drop_column('integration_outbox', 'max_retries')
    op.drop_column('integration_outbox', 'id')
    op.drop_index('ix_comm_log_tenant_status', table_name='communication_logs')
    op.drop_index('ix_oper_kpi_tenant_date', table_name='analytics_operational_daily_kpi')
    op.drop_index('ix_fin_kpi_tenant_date', table_name='analytics_financial_daily_kpi')
    op.drop_index('ix_comm_kpi_tenant_date', table_name='analytics_communication_daily_kpi')
    op.create_table('pricing_price_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('old_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('new_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pricing_price_history_pkey'))
    )
    op.create_index(op.f('ix_pricing_price_history_tenant_id'), 'pricing_price_history', ['tenant_id'], unique=False)
    op.create_table('analytics_events_processed',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_processed_pkey')),
    sa.UniqueConstraint('tenant_id', 'event_id', name=op.f('uq_analytics_event_processed_tenant_event'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_analytics_events_processed_tenant_id'), 'analytics_events_processed', ['tenant_id'], unique=False)
    op.create_table('khata_ledgers',
    sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('reference_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('khata_ledgers_pkey')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name=op.f('uq_khata_ledger_tenant_idempotency'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_khata_ledgers_tenant_id'), 'khata_ledgers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_khata_ledgers_customer_id'), 'khata_ledgers', ['customer_id'], unique=False)
    op.create_table('khata_customer_balances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('outstanding_balance', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('last_ledger_entry_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('last_rebuilt_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('khata_customer_balances_pkey')),
    sa.UniqueConstraint('tenant_id', 'customer_id', name=op.f('uq_khata_balance_tenant_customer'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_khata_customer_balances_tenant_id'), 'khata_customer_balances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_khata_customer_balances_customer_id'), 'khata_customer_balances', ['customer_id'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bird_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('quantity_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('mortality_kg', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('inventory_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_pkey'))
    )
    op.drop_index('ix_conv_state_user', table_name='conversation_state')
    op.drop_table('conversation_state')
    op.drop_index(op.f('ix_pricing_history_tenant_id'), table_name='pricing_history')
    op.drop_table('pricing_history')
    op.drop_index(op.f('ix_khata_ledger_tenant_id'), table_name='khata_ledger')
    op.drop_index('ix_khata_ledger_tenant_customer', table_name='khata_ledger')
    op.drop_index(op.f('ix_khata_ledger_customer_id'), table_name='khata_ledger')
    op.drop_table('khata_ledger')
    op.drop_index(op.f('ix_khata_invoice_tenant_id'), table_name='khata_invoice')
    op.drop_index(op.f('ix_khata_invoice_invoice_id'), table_name='khata_invoice')
    op.drop_index(op.f('ix_khata_invoice_customer_id'), table_name='khata_invoice')
    op.drop_table('khata_invoice')
    op.drop_index(op.f('ix_customer_balance_projection_tenant_id'), table_name='customer_balance_projection')
    op.drop_index(op.f('ix_customer_balance_projection_customer_id'), table_name='customer_balance_projection')
    op.drop_table('customer_balance_projection')
    op.drop_index(op.f('ix_analytics_event_processed_tenant_id'), table_name='analytics_event_processed')
    op.drop_table('analytics_event_processed')
    # ### end Alembic commands ###
