"""add oauth fields

Revision ID: e1b2c3d4e5f6
Revises: d5b16e54ad00
Create Date: 2026-07-16 07:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b2c3d4e5f6'
down_revision = 'd5b16e54ad00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True, server_default='local'))
    op.add_column('users', sa.Column('provider_user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_users_provider_user_id', 'users', ['provider_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_provider_user_id', 'users', type_='unique')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'provider_user_id')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
