import uuid
import enum
from datetime import datetime, timezone
from sqlalchemy import String, DateTime, ForeignKey, Enum
from sqlalchemy.orm import Mapped, mapped_column, relationship
from models.base import Base

class InviteSource(str, enum.Enum):
    QR_DASHBOARD = "QR_DASHBOARD"
    QR_DRIVER = "QR_DRIVER"

class InviteStatus(str, enum.Enum):
    GENERATED = "GENERATED"
    OPENED = "OPENED"
    ONBOARDING = "ONBOARDING"
    USED = "USED"
    EXPIRED = "EXPIRED"
    CANCELLED = "CANCELLED"

class RetailerInvitation(Base):
    """Represents a unique onboarding invitation generated by a wholesaler."""
    __tablename__ = "retailer_invitations"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False)
    invite_code: Mapped[str] = mapped_column(String(20), unique=True, index=True, nullable=False)
    
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    
    source: Mapped[InviteSource] = mapped_column(
        Enum(InviteSource, name="invite_source", create_constraint=True, values_callable=lambda obj: [e.value for e in obj]), 
        nullable=False, default=InviteSource.QR_DASHBOARD
    )
    status: Mapped[InviteStatus] = mapped_column(
        Enum(InviteStatus, name="invite_status", create_constraint=True, values_callable=lambda obj: [e.value for e in obj]), 
        nullable=False, default=InviteStatus.GENERATED
    )
    
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships
    tenant = relationship("Tenant")
    created_by = relationship("User", foreign_keys=[created_by_user_id])
    onboarding_drafts = relationship("RetailerOnboardingDraft", back_populates="invitation")
